# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - Utf8String
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - Utf8String
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

variables:
  - template: /eng/pipelines/common/variables.yml

jobs:
#
# Checkout repository
#
- template: /eng/pipelines/common/checkout-job.yml

#
# Build with Debug config and checked runtimeConfiguration
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: checked
    platforms:
    - Linux_x64
    - Windows_NT_x64
    jobParameters:
      testGroup: innerloop
      buildArgs: -s clr+libs+installer -c debug -runtimeConfiguration checked
      extraStepsTemplate: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml

#
# Build with Release config and Release runtimeConfiguration
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: Release
    platforms:
    - Linux_x64
    - Windows_NT_x64
    jobParameters:
      testGroup: innerloop
      buildArgs: -s clr+libs+installer -c $(_BuildConfig)
      extraStepsTemplate: /eng/pipelines/runtimelab/runtimelab-post-build-steps.yml

#
# Build with Release allConfigurations to produce packages and run tests
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    buildConfig: release
    platforms:
    - Windows_NT_x64
    jobParameters:
      testGroup: innerloop
      nameSuffix: All_Configurations
      buildArgs: -s clr.corelib+libs -c $(_BuildConfig) -allConfigurations

#
# CoreCLR Test builds using live libraries release build
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/templates/runtimes/build-test-job.yml
    buildConfig: checked
    platforms:
    - Linux_x64
    jobParameters:
      testGroup: innerloop
      liveLibrariesBuildConfig: Release
      overrideDependsOn: true
      dependsOn:
      - build_Linux_x64_checked_
      - build_Linux_x64_Release_

#
# Libraries Test Build
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/libraries/build-test-job.yml
    buildConfig: Release
    platforms:
    - Linux_x64
    jobParameters:
      isOfficialBuild: false
      liveRuntimeBuildConfig: Release
      testScope: innerloop
      overrideDependsOn: true
      dependsOn:
      - build_Linux_x64_Release_

- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/libraries/build-test-job.yml
    buildConfig: Release
    platforms:
    - Windows_NT_x64
    jobParameters:
      isOfficialBuild: false
      liveRuntimeBuildConfig: Release
      testScope: innerloop
      overrideDependsOn: true
      dependsOn:
      - build_Windows_NT_x64_Release_

#
# Libraries Release Test Execution against a release coreclr runtime
# Only when the PR contains a libraries change
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/libraries/run-test-job.yml
    buildConfig: Release
    platforms:
    - Linux_x64
    helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
    jobParameters:
      isOfficialBuild: false
      testScope: innerloop
      liveRuntimeBuildConfig: Release
      dependsOnTestBuildConfiguration: Release
      dependsOnTestArchitecture: x64
      overrideDependsOn: true
      dependsOn:
      - libraries_test_build_Linux_x64_Release

- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/libraries/run-test-job.yml
    buildConfig: Release
    platforms:
    - Windows_NT_x64
    helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
    jobParameters:
      isOfficialBuild: false
      testScope: innerloop
      liveRuntimeBuildConfig: Release
      dependsOnTestBuildConfiguration: Release
      dependsOnTestArchitecture: x64
      overrideDependsOn: true
      dependsOn:
      - libraries_test_build_Windows_NT_x64_Release
